version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: notes_mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: appuser
      MONGO_INITDB_ROOT_PASSWORD: apppassword
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:alpine
    container_name: notes_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data:
